backend:
  name: github
  repo: "lolcopter3000/thkerr"
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "gigs"
    label: "work"
    folder: "content/gigs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - { label: "Title / Work Name", name: "title", widget: "string" }
      - { label: "Draft / Hide from site", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Length / Duration", name: "length", widget: "string", required: false, hint: "e.g., 35m, 1hr 10m" }
      - { label: "Start Date / Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "End Date (Optional for date ranges)", name: "end_date", widget: "datetime", format: "YYYY-MM-DD", required: false }
      - { label: "10w summary", name: "summary", widget: "string", required: false }
      - label: "Categories / Tags"
        name: "categories"
        widget: "select"
        multiple: true
        options:
          - { label: "composition", value: "composition" }
          - { label: "performance", value: "performance" }
          - { label: "music release", value: "music release" }
          - { label: "theatre", value: "theatre" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Where", name: "location", widget: "string", required: false }
      - { label: "More info", name: "notes", widget: "text", required: false }
      - { label: "Link", name: "ticket_link", widget: "string", required: false }